### PR TITLE
fix(pluginutils): attach scope object to for-loop

### LINKED ISSUE #547: [pluginutils] attachScopes ignores variables declared in for-of statement
- Rollup Plugin Name: pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10 x64
- Node Version: v13.8.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/BasicMidnightblueAmoebas#index.js

### Expected Behavior

The local scope should contain variable `a`.

### Actual Behavior

The local scope doesn't contain variable `a`.

### Additional Information

It has been reported once but the issue is closed:
https://github.com/rollup/plugins/issues/113

### LINKED ISSUE #548: [pluginutils] attachScopes leaks for-loop variables defined with const/let to outer scope
- Rollup Plugin Name:  pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10
- Node Version: 13.8.0
- Link to reproduction _(⚠️ read below)_:  
  * ForStatement: https://repl.it/repls/StaidAvariciousFactor
  * ForInStatement: https://repl.it/repls/ElatedWelllitCharacters

### Expected Behavior

The outer scope shouldn't contain variable `a` thus it should print

```
false
true
```

### Actual Behavior

```
true
true
```

### Additional Information

It has been reported once but the issue is closed:
#113

### LINKED ISSUE #549: [pluginutils] attachScopes should add scope object to ForStatement.test and ForStatement.update
- Rollup Plugin Name: pluginutils
- Rollup Plugin Version: 4.0.0
- Rollup Version:
- Operating System (or Browser): Windows 10
- Node Version: 13.8.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/WeightyUnnaturalBoolean

### Expected Behavior

With the following code, 
```js
for (let a = 0; a < 10; a++) {
  console.log(a);
  let b = 10;
}
```
There are two different scopes. ForStatement.body (i.e. BlockStatement) can access variable `a` and variable `b`. However, ForStatement.test and ForStatement.update (i.e. BinaryExpression and UpdateExpression) can only access variable `a`.

### Actual Behavior

`attachScopes` only attaches scope object to BlockStatement

### PR DESCRIPTION
**Pull request by eight04**
## Rollup Plugin Name: `pluginutils`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: Fixes #547, fixes #548, fixes #549

### Description

This PR adds a new behavior to `attachScopes`. It creates a new scope object for `ForStatement`, `ForInStatement`, and `ForOfStatement`. IDK if this should be considered as a breaking change.

### CODE REVIEW

File: packages/pluginutils/test/attachScopes.ts [hunk 1]
```diff
@@ -70,3 +70,76 @@ test('supports catch without a parameter', (t) => {
...
+test('supports ForStatement', (t) => {
+  const ast = (parse(
+    `
+    for (let a = 0; a < 10; a++) {
+      console.log(a);
+      let b = 10;
+    }
+  `,
+    { ecmaVersion: 2020, sourceType: 'module' }
+  ) as unknown) as import('estree').Program;
```
Comment (lukastaegert) [inline packages/pluginutils/test/attachScopes.ts:83]: Wouldn't it be nicer to just

```js
import {Program, ForStatement,...} from 'estree'
```

once at the top?

File: packages/pluginutils/test/attachScopes.ts [hunk 2]
```diff
@@ -70,3 +70,76 @@ test('supports catch without a parameter', (t) => {
...
+
+  const scope = attachScopes(ast, 'scope');
+  t.falsy(scope.contains('a'));
+  t.falsy(scope.contains('b'));
+
+  const forLoop = ast.body[0] as import('estree').ForStatement & Record<string, any>;
```
Comment (lukastaegert) [inline packages/pluginutils/test/attachScopes.ts:89]: How about `as ForStatement & {scope: AttachedScope}`, using the type that attachScopes itself uses?

File: packages/pluginutils/test/attachScopes.ts (hunk 1 above)
Comment (lukastaegert) [reply packages/pluginutils/test/attachScopes.ts:83]: Also, shouldn't this make "`estree`" and explicit dependency in the `package.json` file?

**Review by lukastaegert — APPROVED** [review]
Looks good, just some minor type-related comments

File: packages/pluginutils/test/attachScopes.ts (hunk 1 above)
Comment (eight04) [reply packages/pluginutils/test/attachScopes.ts:83]: I'm not familiar with typescript so these were copied from:
https://github.com/rollup/plugins/blob/dbececf6c72bb6276f2a80f35a49bbc7a388ace3/packages/pluginutils/src/attachScopes.ts#L64
Should we also move them to the top?

Comment (lukastaegert) [reply packages/pluginutils/test/attachScopes.ts:83]: Ah I see, I did not notice that one. So `Node` is special in so far as it is also a builtin type so one should be careful to override it, this can cause confusion. Maybe in that case just use a start import instead (works for types just like regular things):

```
import * as estree from 'estree';
```

and then below you use e.g. `estree.Node` or `estree.ForStatement`. Also do not forget to install estree es devDependency, which you should do via `pnpm install -D estree` from the package directory so that the lockfile is updated.

File: packages/pluginutils/package.json [hunk 3]
```diff
@@ -48,14 +48,14 @@
...
   "dependencies": {
-    "@types/estree": "0.0.45",
     "estree-walker": "^2.0.1",
     "picomatch": "^2.2.2"
   },
   "devDependencies": {
     "@rollup/plugin-commonjs": "^14.0.0",
     "@rollup/plugin-node-resolve": "^8.4.0",
     "@rollup/plugin-typescript": "^5.0.2",
+    "@types/estree": "0.0.45",
```
Comment (eight04) [inline packages/pluginutils/package.json:58]: I ended up adding `@types/estree` instead of `estree`

File: packages/pluginutils/src/attachScopes.ts [hunk 4]
```diff
@@ -1,3 +1,6 @@
+// eslint-disable-next-line import/no-unresolved
+import * as estree from 'estree';
+
 import { walk } from 'estree-walker';
```
Comment (eight04) [inline packages/pluginutils/src/attachScopes.ts:4]: This was copied from https://github.com/rollup/plugins/blob/dbececf6c72bb6276f2a80f35a49bbc7a388ace3/packages/pluginutils/types/index.d.ts#L1-L2

**Review by lukastaegert — APPROVED** [review]
Looks good to go from my side!

**Review by shellscape — APPROVED** [review]

**Comment by shellscape** [comment]
thanks!
