### PR TITLE
fix(node-resolve): Fix package exports / imports resolution algorithm

### LINKED ISSUE #1476: [node-resolve] * in exports key can't correctly resolved
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 15.0.2
- Rollup Version: 3.7.5
- Operating System (or Browser): MacOS 13.3 Ventura
- Node Version: 18.5.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-t8bmex

### Expected Behavior

`node packages/app/src/main.js` works fine:

image

Built by vite is also works, because vite use self vite:resolve plugin:

`pnpm -F app build:vite`:

Rollup should build without warnings.

### Actual Behavior

But rollup can't resolve:

image

### Additional Information

This issue is found when I test package.exports field:

```
{
  "name": "utils",
  "type": "module",
  "exports": {
    "./a/*/c": "./abc.js"
  }
}
```

### LINKED ISSUE #1548: [node-resolve] Can not resolve exports with extension
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 15.1.0
- Rollup Version: 3.27.0
- Operating System (or Browser): Linux
- Node Version: 20.3.1
- Link to reproduction _(⚠️ read below)_: https://github.com/susnux/node-exports-demo-rollup

### Expected Behavior

Rollup can resolve exports with extensions like:
```js
import { foo } from 'dummy-exported/foo.js'
```

with exports like this:
```json
{
  "name": "dummy-exported",
  "version": "1.0.0",
  "exports": {
    "./*.js": {
      "import": "./dist/*.mjs",
      "require": "./dist/*.cjs"
    }
  }
}
```

### Actual Behavior

```
(!) Plugin node-resolve: Could not resolve import "dummy-exported/foo.js" in /tmp/a/src/main.js using exports defined in /tmp/a/node_modules/dummy-exported/package.json.
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
dummy-exported/foo.js (imported by "src/main.js")
```

### Additional Information

See linked repository to reproduce the issue. You can also see that the exports section is correct, because Node can resolve the module correctly (see by running inside the example):
```sh
node ./src/main.js
```

### PR DESCRIPTION
**Pull request by susnux**
## Rollup Plugin Name: `node-resolve`

This PR contains:

- [x] bugfix
- [ ] feature
- [x] refactor
- [x] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
* Fixes #1548 
* Fixes #1476

### Description

Currently the implementation of package exports / imports resolution does not follow the Node documentation as the README implies.
So this fixes the package exports and imports resolution algorithm by strictly following the Node API documentation. For backwards compatibility a new option `allowExportsFolderMapping` is introduced which will enable deprecated folder mappings.

This is required for packages that use export patterns with the asterisk in the middle not at the end, like this:
```json
{
  "exports": {
    "./component/*.js": {
      "import": "./dist/*.mjs",
      "require": "./dist/*.cjs"
    }
  }
}
```

See included test file.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. @guybedford is our resident resolutions expert, hoping he sees this and offers thoughts.

File: packages/node-resolve/src/package/resolvePackageImportsExports.ts [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+  if (rval !== 0) return rval;
+
+  // If keyA does not contain "*", return 1.
+  if (!keyA.includes('*')) return 1;
+  // If keyB does not contain "*", return -1.
+  if (!keyB.includes('*')) return -1;
+
+  // If the length of keyA is greater than the length of keyB, return -1.
+  // If the length of keyB is greater than the length of keyA, return 1.
+  // --> both keys do not contain * so baseLength of both is the key length, so this is already handled by `rval` above
```
Comment (lukastaegert) [inline packages/node-resolve/src/package/resolvePackageImportsExports.ts:26]: True, but if order is important here (I did not check the original algorithm), then length is now checked before the presence of `*` instead of after. Is this fine?

**Review by lukastaegert — COMMENTED** [review]
This really looks massive and appears to contain many subtle improvements. It also appears you checked against the original algorithm, is that true?
Admittedly, the TypeScript conversion both is very useful and makes comparing the diff rather hard. For other reviewers, the relevant files to look at are resolvePackageImportsExports.ts and resolvePackageTarget.ts as only those contain major changes.

I do not feel confident to 100% judge the accuracy of the algorithm, but I would hope this feature can land as it seems to fix everything that might subtly differ from the Node algorithm.

File: packages/node-resolve/src/package/resolvePackageImportsExports.ts (hunk 1 above)
Comment (guybedford) [reply packages/node-resolve/src/package/resolvePackageImportsExports.ts:26]: Good catch @lukastaegert - both keys contain `*` here so I think we do need to still do the comparison as per the original algorithm, since the greater specificity when the bases are equal is taken to be the one with the more specific trailer.

File: packages/node-resolve/src/package/resolvePackageImportsExports.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+    const target = matchObj[matchKey];
+    // Return the result of PACKAGE_TARGET_RESOLVE(packageURL, target, null, isImports, conditions).
+    const resolved = await resolvePackageTarget(context, { target, patternMatch: '', isImports });
+    return resolved;
+  }
+
+  // Let expansionKeys be the list of keys of matchObj containing only a single "*"
+  const expansionKeys = Object.keys(matchObj)
+    // Assert: ends with "/" or contains only a single "*".
+    .filter((k) => k.endsWith('/') || k.includes('*'))
```
[the remark this answers is not in the document]
Comment (guybedford) [reply packages/node-resolve/src/package/resolvePackageImportsExports.ts:53]: This is how the algorithm is written - basically multiple `**` are invalid, but we don't ban them outright in case it might be supported in future - so instead they are filtered out by omission since they can never be matched.

**Review by guybedford — APPROVED** [review]
Sorry didn't spot this at first. Great to have the spec comments in here - this is excellent work thank you!

**Comment by shellscape** [comment]
@lukastaegert I'll leave this one up to you to merge when you're happy with the convo with @guybedford

File: packages/node-resolve/src/package/resolvePackageImportsExports.ts (hunk 1 above)
Comment (susnux) [reply packages/node-resolve/src/package/resolvePackageImportsExports.ts:26]: Good catch, asked myself why the spec has this useless condition, but I simply missed the not.

At this position both keys contain a `*` so we really need to use the full key length of both.
```suggestion
  // If the length of keyA is greater than the length of keyB, return -1.
  // If the length of keyB is greater than the length of keyA, return 1.
  return keyB.length - keyA.length
```

**Comment by susnux** [comment]
@lukastaegert @guybedford Thank you very much for your review!
I fixed the sorting as per spec.

**Review by lukastaegert — APPROVED** [review]
Looks good from my side
