### PR TITLE
fix(commonjs): handle `node:` builtins with `strictRequires: auto`

### LINKED ISSUE #1929: [commonjs] "default" is not exported by some node core modules with `strictRequires: 'auto'`
- Rollup Plugin Name: `@rollup/plugin-commonjs`
- Rollup Plugin Version: v28.0.8
- Rollup Version: 4.52.4
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-w9uxyy67?file=src%2Fmain.js,rollup.config.js

### Expected Behavior

With this config:

```
commonjs({
  strictRequires: 'auto',
}),
```

we now have an error when importing default export of some node core modules:

```ts
new (require('node:stream').Readable)({});
// throws RollupError: "default" is not exported by "node:stream?commonjs-external"
```

This worked fine with v28.0.6

### Additional Information

This is code from `@vue/server-renderer`, which means that we spotted the issue in a renovate PR upgrade for Nuxt: https://github.com/nuxt/nuxt/pull/33469.

### PR DESCRIPTION
**Pull request by danielroe**
## Rollup Plugin Name: `@rollup/plugin-commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

resolves #1929

### Description

this fixes an issue introduced in #1909, which added special handling for `node:` builtins to avoid eager loading in wrapped modules...

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. Please take some time to describe what your changes do differently. 

We're also discussing this in https://github.com/rollup/plugins/issues/1924

**Comment by danielroe** [comment]
my apologies!

charlie's summary in the linked issue and the code comment in this PR cover what i was intending, but i'll write in more detail when i'm back at my computer

File: packages/commonjs/src/resolve-require-sources.js [hunk 1]
```diff
@@ -196,16 +196,21 @@ export function getRequireResolver(extensions, detectCyclesAndConditional, curre
           // Special-case external Node built-ins to be handled via a lazy __require
           // helper instead of hoisted ESM imports when strict wrapping is used.
           const isExternalWrapped = isWrappedId(dependencyId, EXTERNAL_SUFFIX);
-          if (
-            parentMeta.initialCommonJSType === IS_WRAPPED_COMMONJS &&
-            !allowProxy &&
-            isExternalWrapped
-          ) {
+          let resolvedDependencyId = dependencyId;
+          if (parentMeta.isCommonJS === IS_WRAPPED_COMMONJS && !allowProxy && isExternalWrapped) {
```
Comment (danielroe) [inline packages/commonjs/src/resolve-require-sources.js:200]: 1. Previously, we checked `parentMeta.initialCommonJSType === IS_WRAPPED_COMMONJS` instead of `parentMeta.isCommonJS === IS_WRAPPED_COMMONJS`. With strictRequires: 'auto', I believe the initial type (before cycle detection) can differ from the final type.

File: packages/commonjs/src/resolve-require-sources.js [hunk 2]
```diff
@@ -196,16 +196,21 @@ export function getRequireResolver(extensions, detectCyclesAndConditional, curre
...
               parentMeta.isRequiredCommonJS[dependencyId] = isCommonJS;
             }
+          } else if (isExternalWrapped && !allowProxy) {
+            // If the parent is not wrapped but the dependency is a node: builtin external,
+            // unwrap the EXTERNAL_SUFFIX so it's treated as a normal external.
+            // This avoids trying to load the lazy __require proxy for non-wrapped contexts.
+            const actualExternalId = unwrapId(dependencyId, EXTERNAL_SUFFIX);
+            if (actualExternalId.startsWith('node:')) {
+              resolvedDependencyId = actualExternalId;
+            }
```
Comment (danielroe) [inline packages/commonjs/src/resolve-require-sources.js:213]: 2. `node:` builtins with the EXTERNAL_SUFFIX were always loaded with `getExternalBuiltinRequireProxy()` which only exports `__require()`. However, when the parent module is not wrapped (no cycles detected with strictRequires: 'auto'), the generated code tried to import a default export that didn't exist.

(so in this case we can remove the suffix)

**Comment by shellscape** [comment]
thanks!
