### PR TITLE
fix(commonjs): fix interop when importing CJS that is a transpiled ES module from an actual ES module

### LINKED ISSUE #411: [commonjs] cross import between entry commonjs modules is broken
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: Latest
- Rollup Version: Latest
- Operating System (or Browser): MacOS, Repl.it
- Node Version: v12.16.3

### How Do We Reproduce?

https://repl.it/@csr632/rollup-plugin-repro

### Expected Behavior
checkout `dist/test1.js` , it access test2 module as `test2.__moduleExports`, which is clearly undefined.

### Actual Behavior
`dist/test1.js` should log `test2` correctly

Output format is esm, so maybe related to https://github.com/rollup/plugins/issues/400. But in my case, I have multi entry modules.

### LINKED ISSUE #454: Regression @rollup/plugin-commonjs v13.0.0
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: v13.0.0
- Rollup Version: 1.32.1
- Operating System (or Browser): any
- Node Version: any

### How Do We Reproduce?

https://repl.it/repls/PhonyUsefulNanotechnology#output/bundle.js

Have a file like 
```js
import {LitElement, html} from "lit-element"
import { useState } from "lit-element-state-decoupler";
import {useOnce} from "lit-element-effect";

export class Element extends LitElement {
  render() {
    const {getState, publish} = useState(this, false)
    useOnce(this, () => publish(true))

    return html`<div>Called: ${getState()}<div>`
  }
}
```

### Expected Behavior

The imports are resolved correctly. In the bundle that would create a result: 

```js
class Element extends LitElement {
  render() {
    const {getState, publish} = index.useState(this, false);
    index$1.useOnce(this, () => publish(true));

    return html`<div>Called: ${getState()}<div>`
  }
}

```

(Note the `index$1` on `useOnce`)

### Actual Behavior

`useOnce` is retrieved from `index`, which obviously fails:

```js
class Element extends LitElement {
  render() {
    const {getState, publish} = index.useState(this, false);
    index.useOnce(this, () => publish(true));

    return html`<div>Called: ${getState()}<div>`
  }
}

```

### Workaround

Use version 12.0.0 of @rollup/plugin-commonjs instead of v13.0.0

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
Part of #481 
Resolves #411 
Resolves #454 

### Description
The main part of this PR is to re-introduce proper interop handling when importing transpiled ESM files, i.e. CJS files with `exports.__esModule: true`. It now relies on a new Rollup feature to take synthetic named exports from an arbitrary export, in this case `__moduleExports`. This export will not become part of the public interface of entry points and not show up in reified namespace objects.

In contrast to what I wrote in #481, I again used an interop function because due to the PURE annotation, it allowed for better tree-shaking. The interop I used is actually identical to the old one, which means if there is no `default` property, the default export falls back to the namespace. This is not according to specs but is needed to prevent consumers that use Rollup's old interop pattern from failing, see the comment I added in the code and rollup/rollup-plugin-commonjs#224
A breaking change I added is that now CJS files will again always expose a default export, even if they are entry points. The reason is that the old logic was very error prone and often did not detect reliably if later dependencies would import something from an entry point. Once we add the `exposedExports` option I recommended in #481, this should be easily fixable manually by the user. For now, they can just use an ESM wrapper as their entry point.

Also, I changed how the helpers are imported when using dynamic requires. More precisely, I added an ad-hoc wrapper that just reexports the `commonjsRegister` helper as default export and required that from CJS which prevented the creation of an unneeded namespace object and allowed unused helpers to be tree-shaken away.

Last, I updated all dependencies as I needed to update the Rollup dependency anyway. Another breaking change is the new peer dependency version of Rollup.

Due to the pressing nature of this fix I would recommend to release rather sooner than later, even though the other fixes in #481 will likely need yet another major version.

### CODE REVIEW

**Comment by lukastaegert** [comment]
This is now ready for review and could potentially be released as a new major. The rollup peer dependency has been updated to `^2.22.0`.

**Comment by lukastaegert** [comment]
Apparently some local paths were re-introduced into the bundle, I will need to check that. Back to draft it is.

**Comment by lukastaegert** [comment]
Ok, all fixed now, please have a look. I very much recommend studying the diff of the function test snapshots at https://github.com/rollup/plugins/pull/501/files#diff-b197c1539f3dea1e33fceb0a1ace63f3 as they can explain the nature of the changes better, and also take a look at the added tests.

File: packages/commonjs/test/fixtures/function/dynamic-require-resolve-index/_config.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-const nodeResolve = require('@rollup/plugin-node-resolve');
+const { nodeResolve } = require('@rollup/plugin-node-resolve');
```
Comment (danielgindi) [inline packages/commonjs/test/fixtures/function/dynamic-require-resolve-index/_config.js:1]: Why have you switched to importing the named export in favor of the default export?
Is it just to be explicit or didn't it work anymore with the default export?
I know that it exports both, but we need to be sure that nothing has been fatally broken :-)

**Comment by danielgindi** [comment]
This will be difficult to test with all situations people has experienced out there. Can we tag some people who reported issues so they'll test it live?

File: packages/commonjs/test/snapshots/function.js.md [hunk 2]
```diff
@@ -179,6 +142,12 @@ Generated by [AVA](https://ava.li).
       var foo_bar = 'fubar';␊
       ␊
       t.is(foo_bar, 'fubar');␊
+      ␊
+      var main = {␊
+      ␊
+      };␊
+      ␊
+      module.exports = main;␊
```
Comment (danielgindi) [inline packages/commonjs/test/snapshots/function.js.md:150]: Practically there's no difference here right? As it's an empty object vs the default empty exports object...

File: packages/commonjs/test/fixtures/function/dynamic-require-resolve-index/_config.js (hunk 1 above)
Comment (lukastaegert) [reply packages/commonjs/test/fixtures/function/dynamic-require-resolve-index/_config.js:1]: This is not an `import`, this is a CJS `require`. Since a recent version, this plugin switched to named export mode. We could also have used the default export at `.default` but then if we need to use a property anyway, I prefer the named export.

File: packages/commonjs/test/snapshots/function.js.md (hunk 2 above)
Comment (lukastaegert) [reply packages/commonjs/test/snapshots/function.js.md:150]: Good point. This could be an optimization to add.

Comment (lukastaegert) [reply packages/commonjs/test/snapshots/function.js.md:150]: Actually, this could be problematic to get rid of because this plugin converts to ESM and that one does not have an implicit default export. So an empty object is generated. I do not see how Rollup core could get rid of this easily later. I think this would be a job to be fixed manually via an `exposedExports` option.

**Comment by lukastaegert** [comment]
If anyone is interested: In order to test this, you can clone the repo, run `npm link` from the `packages/commonjs` dir and then run `npm link @rollup/plugin-commonjs` in your test repo. Unfortunately as far as I know, direct Github branch installation does not work for mono repos.

**Comment by lukastaegert** [comment]
I can definitely confirm that this PR solves the issue described in #411. The generated `test1.js` is now

```js
import test2 from './test2.js';

console.log(test2);
var test1 = 1;

export default test1;
```

without a reference to `__moduleExports`, while `test2.js` remains unmodified.

**Comment by lukastaegert** [comment]
#491 is still broken, but this was also not intended to be covered here. This PR is only about what an ES module receives when importing a CJS module while #491 is about the inverse case.

**Comment by lukastaegert** [comment]
I can confirm that #454 is also resolved by this PR.

**Comment by lukastaegert** [comment]
#431 is still broken. I might have a look at this one.

**Comment by lukastaegert** [comment]
#400 is not fixed, but again this is the same issue as #491.

**Comment by lukastaegert** [comment]
#431 seems to require a lot of setup to reproduce, I guess it should be addressed in a separate PR. So from my side, I still think this one is good to go.

**Comment by shellscape** [comment]
@lukastaegert I can hold off on publishing this if changes for the other issues you mentioned will also be breaking

**Comment by lukastaegert** [comment]
They will, the question is only when they will be ready...

**Comment by shellscape** [comment]
OK. Let's sit on this one for a short while in the event we get a few more in.

**Comment by guybedford** [comment]
FWIW I disagree with this approach since it does not match Node.js interop and likely never will since Node.js support for named exports is now fully stalled after three separate failed initatives over many years.

**Comment by lukastaegert** [comment]
Noted. But at least for bundlers, handling ES modules that were transpiled to CJS in the same way as the original ES module is very important. This PR fixes the default export handling and brings it more in line with how other bundlers handle it. Named exports existed before and after this PR and were not touched here.

**Comment by guybedford** [comment]
It would help to have a flag to change this behaviour for users who want to bundle Node.js apps. I'm sure an issue will come up at some point in the coming months to track this by someone.

**Comment by lukastaegert** [comment]
Sure, as it has been discussed before, and I very much agree we should have it. Forbidding named exports and preventing interop however is only a small part of this, properly handling `package.exports` and replacing CJS/ESM detection with Node's algorithm would be the bigger one. The main problem is defining a nice way to have the node-resolve and commonjs plugins talk to each other as the former is responsible for package.json information.

**Comment by lukastaegert** [comment]
If we add this, then it should certainly be at least close to the full package, otherwise I am not sure users will see the benefit.

**Comment by guybedford** [comment]
What information from the package is required from the commonjs plugin
perspective?

It should be just the format info in the ambiguous cases, which could in
the worst case be loaded twice with a 15 line package.json boundary check
and load and rely on the process-level file system caching of the operating
system.

**Comment by lukastaegert** [comment]
Finding and resolving package.json files and in extension libraries relying on them is one of the most performance critical parts of bundling, more performance critical than actually loading the files. The node-resolve plugin has excellent caching to avoid any unnecessary directory lookup while also providing the information which package.json file is responsible for a js file. Would be a waste not to reuse this information.
