### PR TITLE
fix(commonjs): preserve the class body property keys even if they are special keywords

### LINKED ISSUE #1682: Parsing fails when a class property is named global
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 25.0.7
- Rollup Version: 4.11.0
- Operating System (or Browser): Linux
- Node Version: 21.6.1
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-y5ambp?file=src%2Fmain.js

### Expected Behavior
Compile normally.

### Actual Behavior
Compilation fails from a parsing error:
```
[!] (plugin commonjs--resolver) RollupError: Unexpected token `.`. Expected * for generator, private key, identifier or async
index.js (2:10)
1: class Foo {
2:     global;
             ^
3: }
4: exports = Foo
    at error (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/parseAst.js:279:30)
    at parseError (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/parseAst.js:1041:9)
    at convertNode (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/parseAst.js:2130:12)
    at convertProgram (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/parseAst.js:1034:12)
    at Object.parseAstAsync (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/parseAst.js:2181:12)
    at Module.tryParseAsync (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/rollup.js:15008:20)
    at Module.setSource (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/rollup.js:14589:35)
    at ModuleLoader.addModuleSource (/home/fire/source/js/test-rollup/node_modules/.pnpm/rollup@4.11.0/node_modules/rollup/dist/shared/rollup.js:18937:13)
```

### Additional Information
Code compiles without the plugin enabled.

### PR DESCRIPTION
**Pull request by TrickyPi**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
resolves #1682

### CODE REVIEW

File: packages/commonjs/test/snapshots/function.js.md [hunk 1]
```diff
@@ -241,6 +241,36 @@ Generated by [AVA](https://avajs.dev).
...
+      function commonjsRequire(path) {␊
+      	throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');␊
+      }␊
+      ␊
+      var main = {};␊
+      ␊
+      class Rollup {␊
+        define = undefined;␊
+        require = commonjsRequire;␊
+        global = commonjsGlobal;␊
```
Comment (lukastaegert) [inline packages/commonjs/test/snapshots/function.js.md:264]: I am not sure this is correct. We were defining a class with properties define, require and global, but as they do not have an initializer, this is not like object shorthand properties but rather they are initialized to undefined, see also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#description

I assume this will just make the code simpler, though.

Comment (TrickyPi) [reply packages/commonjs/test/snapshots/function.js.md:264]: After looking at this again, I find out that the function `commonjsRequire` is not useful. So I agree with you that the `require` property should not be transformed into `require = commonjsRequire`. The `define` property is the same as well. As for `global`, I think it could be transformed into `global = commonjsGlobal` if the option `ignoreGlobal` is not `true`.

Comment (TrickyPi) [reply packages/commonjs/test/snapshots/function.js.md]: Oh, I get it now. Thanks for your patient explanation!

**Review by lukastaegert — APPROVED** [review]
Looks good to me, thanks a lot for fixing!

**Comment by Bisstocuz** [comment]
@shellscape @lukastaegert Hello, when to merge this? This issue prevent us building Discord bot.

https://github.com/rollup/plugins/issues/1682#issuecomment-2120461291
