### PR TITLE
fix(typescript): path validation issue in validatePaths function

### LINKED ISSUE #1790: [rollup-plugin-typescript] Using a nested path for the declarationDir option always throws an error
- Rollup Plugin Name: `rollup-plugin-typescript`
- Rollup Plugin Version: `12.1.1`
- Rollup Version: 4.24.0
- Operating System (or Browser): macOs 14.7
- Node Version: 20.11.1
- Link to reproduction: https://stackblitz.com/edit/rollup-ts-5fhnsy?file=rollup.config.js

### Expected Behavior

When using the `declarationDir` option with a nested path, `npm build` should output the bundled code in the `dist` folder, and the type declarations in the `dist/types` folder.

```js
// rollup.config.js
import typescript from '@rollup/plugin-typescript';

export default {
  input: 'src/main.ts',
  output: [
    { file: 'dist/main.esm.js', format: 'esm' },
    { file: 'dist/main.umd.js', format: 'umd' },
  ],
  plugins: [
    typescript({
      tsconfig: './tsconfig.json',
      compilerOptions: {
        target: 'es6',
        baseUrl: './',
        outDir: './dist',
        declaration: true,
        declarationDir: './dist/types',
      },
    }),
  ],
};
```

This was working in `12.1.0`, as seen here: https://stackblitz.com/edit/rollup-ts-afeykb?file=rollup.config.js

### Actual Behavior

In `12.1.1`, the command fails with the following error:

```
[!] (plugin typescript) RollupError: [plugin typescript] @rollup/plugin-typescript: Path of Typescript compiler option 'declarationDir' must be located inside the same directory as the Rollup 'file' option.
```

### Additional Information

I tried different combinations of relative paths for both `outDir` and `declarationDir`, but none worked:

- `outDir: 'dist'` and `declarationDir: 'dist/types'`
- `outDir: './dist'` and `declarationDir: 'dist/types'`
- `outDir: 'dist'` and `declarationDir: './dist/types'`
- `outDir: './dist'` and `declarationDir: './dist/types'`
- `outDir: 'dist'` and `declarationDir: 'types'`
- `outDir: './dist'` and `declarationDir: 'types'`
- `outDir: 'dist'` and `declarationDir: './types'`
- `outDir: './dist'` and `declarationDir: './types'`

The only combination that works is using `dist` for both, but that defeats the purpose of having the types in a nested folder:

- `outDir: 'dist'` and `declarationDir: 'dist'`

### PR DESCRIPTION
**Pull request by JaCraig**
## Rollup Plugin Name: `@rollup/plugin-typescript`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

 resolves #1790

### Description

In the @rollup/plugin-typescript plugin, current code allows paths that are below the 'file' option but not nested directories. For example if file option is set to "C:/examplelib/output" directory, then "C:/examplelib" is fine while "C:/examplelib/output/decl" is not. The order change in this commit fixes this issue introduced in 12.1.1.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. Looks like you've got some test failures in Windows.

File: packages/typescript/src/options/validate.ts [hunk 1]
```diff
@@ -65,8 +65,13 @@ export function validatePaths(
             `@rollup/plugin-typescript: Path of Typescript compiler option '${dirProperty}' must be located inside Rollup 'dir' option.`
           );
         }
+      } else if(dirProperty === 'outDir') {
+        const fromTsDirToRollup = relative(compilerOptions[dirProperty],outputDir);
+        if (fromTsDirToRollup.startsWith('..')) {
+            context.error(`@rollup/plugin-typescript: Path of Typescript compiler option '${dirProperty}' must be located inside the same directory as the Rollup 'file' option.`);
```
Comment (shellscape) [inline packages/typescript/src/options/validate.ts:71]: since we've added a new condition here, please add a test where there _is_ an error produced. that will help prevent regressions in the future.

**Review by shellscape — APPROVED** [review]
