### PR TITLE
fix(node-resolve): forward meta-information from other plugins

### LINKED ISSUE #1060: node-resolve wipes out other plugins' meta data
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 13.0.6
- Rollup Version: 2.60.1
- Operating System (or Browser): Windows 10
- Node Version: 14.17.6
- Link to reproduction _(⚠️ read below)_: https://replit.com/@Septh/node-resolve-meta-issue-repro

### Expected Behavior
Meta data added by other plugins is respected.

### Actual Behavior
Meta data is removed.

### Additional Information
It all depends on plugins order - run REPL for a demo.

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `node-resolve`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
Resolves #1060 

### Description
While node-resolve was already calling other resolvers to allow them to mark modules as external, meta-information was ignored so far. This fix will make sure that all meta information added by other plugins is preserved (except moduleSideEffects that is).

### CODE REVIEW

**Review by tjenkinson — COMMENTED** [review]
Is the reason this fix is needed because the resolve id hooks are only ever called once?

So without the `this.resolve` the other resolve id hooks would be called from somewhere else, where the returned metadata was respected there?

**Comment by lukastaegert** [comment]
> So without the this.resolve the other resolve id hooks would be called from somewhere else

Actually, they would not be called at all for plugins that are sorted *after* the node-resolve plugin, because, as you stated, resolution only happens once. We needed to add `this.resolve` here because it allowed people to mark ids as external that had been resolved by node-resolve. Another solution would have been to place the other plugin always before node-resolve, but these ordering-solutions are tricky. Yet another solution is for the plugin to use the `options` hook to add a secondary plugin that is placed first.
But as we decided to go for this solution, respecting the meta data added by other plugins besides the `external` flag seemed like a small step.
The only things that are NOT respected are the `id` and `moduleSideEffects`. `moduleSideEffects` is necessary, because node-resolve determines this value and we have no way to figure out if other plugins respected that value or not. The reason we also ignore `id` changes was linked for me: If I change the id, `moduleSideEffects` may be completely wrong as it was based on the position of the original module in the file system.

File: packages/node-resolve/src/index.js [hunk 1]
```diff
@@ -267,9 +266,13 @@ export function nodeResolve(opts = {}) {
...
-        const isExternal = !!(resolvedResolved && resolvedResolved.external);
-        if (isExternal) {
-          return false;
+        if (resolvedResolved) {
+          // Handle plugins that manually make the result external
+          if (resolvedResolved.external) {
+            return false;
+          }
+          // Pass on meta information added by other plugins
+          return { ...resolvedResolved, moduleSideEffects: resolved.moduleSideEffects };
```
Comment (tjenkinson) [inline packages/node-resolve/src/index.js:275]: given what you said before

>The only things that are NOT respected are the id and moduleSideEffects

shouldn't you be forcing `resolved.id` as the id here too?

File: packages/node-resolve/src/index.js [hunk 2]
```diff
@@ -267,9 +266,13 @@ export function nodeResolve(opts = {}) {
...
         );
-        const isExternal = !!(resolvedResolved && resolvedResolved.external);
-        if (isExternal) {
-          return false;
+        if (resolvedResolved) {
+          // Handle plugins that manually make the result external
+          if (resolvedResolved.external) {
+            return false;
+          }
+          // Pass on meta information added by other plugins
```
Comment (tjenkinson) [inline packages/node-resolve/src/index.js:274]: I wonder if we should really just target property holding the metadata instead of allowing everything through by default except `moduleSideEffects`? Don't think we'd be doing any object merging then

**Review by tjenkinson — APPROVED** [review]
thanks for the explanation. I think you might have missed overriding the `id` based on what you said?

I'm not sure what the best answer is to my other comment. Not defaulting to passing all props through feels safer and more controlled, but maybe it's fine. You have a much better understanding of the API than I do :)

LGTM!

File: packages/node-resolve/src/index.js (hunk 2 above)
Comment (lukastaegert) [reply packages/node-resolve/src/index.js:274]: Admittedly, the last remaining property is `syntheticNamedExports`. Which we may want to keep IF we also keep the id. So maybe a better solution is: Keep everything from the second resolve, but override moduleSideEffects if the id did not change?

File: packages/node-resolve/src/index.js (hunk 1 above)
Comment (tjenkinson) [reply packages/node-resolve/src/index.js:275]: I mean 
```suggestion
          return { ...resolvedResolved, id: resolved.id, moduleSideEffects: resolved.moduleSideEffects };
```
?

right now a change to bar.js would make it though and it shouldn’t?

**Comment by shellscape** [comment]
@lukastaegert @tjenkinson please give me a heads up on when you both are satisfied with the state of conversation, so I know when to merge this one.

File: packages/node-resolve/src/index.js (hunk 1 above)
Comment (lukastaegert) [reply packages/node-resolve/src/index.js:275]: Ah, then you are indeed right, should read my own code ^^
I will change it to just pick the meta property, that is probably best for now.

Comment (lukastaegert) [reply packages/node-resolve/src/index.js]: Done, please have another look

**Review by tjenkinson — APPROVED** [review]
Lgtm :shipit:
